# Decap CMS Configuration for Melanie Zeyer Blog
# Based on BlogPost interface from src/types/blog.ts

backend:
  name: git-gateway
  branch: main
  squash_merges: true

# Enable local development backend
local_backend: true

# Media configuration
media_folder: "public/content/blog/images"
public_folder: "/content/blog/images"

# Site configuration
site_url: https://melaniezeyer.de
display_url: https://melaniezeyer.de

# Localization
locale: de

# Editorial workflow for draft/review/publish
publish_mode: editorial_workflow

# Logo configuration
logo_url: /assets/logo.svg

# Collections configuration
collections:
  # Blog Posts Collection
  - name: "blog"
    label: "Blog Beiträge"
    label_singular: "Blog Beitrag"
    folder: "public/content/blog"
    create: true
    delete: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "blog/{{slug}}"
    editor:
      preview: true
    fields:
      # Core content fields
      - { 
          label: "Titel", 
          name: "title", 
          widget: "string", 
          required: true,
          hint: "Der Haupttitel des Blog-Beitrags"
        }
      - { 
          label: "URL-Slug", 
          name: "slug", 
          widget: "string", 
          required: true,
          pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$', "Nur Kleinbuchstaben, Zahlen und Bindestriche"],
          hint: "URL-freundlicher Name für den Beitrag (z.B. mein-erster-blog-post)"
        }
      - { 
          label: "Veröffentlichungsdatum", 
          name: "date", 
          widget: "datetime", 
          required: true,
          date_format: "DD.MM.YYYY",
          time_format: "HH:mm",
          format: "YYYY-MM-DDTHH:mm:ss.SSSZ",
          hint: "Wann soll der Beitrag veröffentlicht werden?"
        }
      - { 
          label: "Zusammenfassung", 
          name: "excerpt", 
          widget: "text", 
          required: true,
          hint: "Kurze Beschreibung des Beitrags (max. 150 Zeichen)"
        }
      - { 
          label: "Autor", 
          name: "author", 
          widget: "string", 
          required: true,
          default: "melanie",
          hint: "Autor-ID des Verfassers"
        }
      
      # Categorization
      - { 
          label: "Kategorie", 
          name: "category", 
          widget: "select", 
          required: true,
          options: [
            { label: "Coaching", value: "coaching" },
            { label: "Persönlichkeitsentwicklung", value: "persoenlichkeitsentwicklung" },
            { label: "Lifestyle", value: "lifestyle" },
            { label: "Business", value: "business" },
            { label: "Gesundheit", value: "gesundheit" },
            { label: "Mindset", value: "mindset" }
          ],
          hint: "Hauptkategorie des Beitrags"
        }
      - { 
          label: "Tags", 
          name: "tags", 
          widget: "list", 
          required: false,
          allow_add: true,
          hint: "Schlagwörter für detailliertere Kategorisierung"
        }
      
      # Featured image
      - { 
          label: "Beitragsbild", 
          name: "image", 
          widget: "image", 
          required: false,
          hint: "Hauptbild für den Beitrag (max. 5MB, JPG/PNG/WebP)"
        }
      - { 
          label: "Bildbeschreibung", 
          name: "imageAlt", 
          widget: "string", 
          required: false,
          hint: "Beschreibung des Bildes für Barrierefreiheit"
        }
      
      # Status and metadata
      - { 
          label: "Status", 
          name: "status", 
          widget: "select", 
          required: true,
          default: "draft",
          options: [
            { label: "Entwurf", value: "draft" },
            { label: "Veröffentlicht", value: "published" },
            { label: "Archiviert", value: "archived" }
          ],
          hint: "Veröffentlichungsstatus des Beitrags"
        }
      - { 
          label: "Hervorgehoben", 
          name: "featured", 
          widget: "boolean", 
          required: false,
          default: false,
          hint: "Als wichtiger Beitrag markieren"
        }
      - { 
          label: "Lesezeit (Minuten)", 
          name: "readingTime", 
          widget: "number", 
          required: false,
          value_type: "int",
          min: 1,
          max: 60,
          hint: "Geschätzte Lesezeit in Minuten (wird automatisch berechnet falls leer)"
        }
      - { 
          label: "Letzte Änderung", 
          name: "lastModified", 
          widget: "datetime", 
          required: false,
          date_format: "DD.MM.YYYY",
          time_format: "HH:mm",
          format: "YYYY-MM-DDTHH:mm:ss.SSSZ",
          hint: "Datum der letzten Bearbeitung"
        }
      
      # SEO fields group
      - label: "SEO Einstellungen"
        name: "seo"
        widget: "object"
        collapsed: true
        required: false
        hint: "Suchmaschinenoptimierung"
        fields:
          - { 
              label: "Meta-Titel", 
              name: "metaTitle", 
              widget: "string", 
              required: false,
              hint: "Titel für Suchmaschinen (max. 60 Zeichen)"
            }
          - { 
              label: "Meta-Beschreibung", 
              name: "metaDescription", 
              widget: "text", 
              required: false,
              hint: "Beschreibung für Suchmaschinen (max. 160 Zeichen)"
            }
          - { 
              label: "Canonical URL", 
              name: "canonicalUrl", 
              widget: "string", 
              required: false,
              hint: "Kanonische URL für doppelte Inhalte"
            }
          - { 
              label: "Open Graph Bild", 
              name: "ogImage", 
              widget: "image", 
              required: false,
              hint: "Bild für Social Media Sharing"
            }
          - { 
              label: "SEO Keywords", 
              name: "keywords", 
              widget: "list", 
              required: false,
              allow_add: true,
              hint: "Schlüsselwörter für Suchmaschinen"
            }
      
      # Main content
      - { 
          label: "Inhalt", 
          name: "body", 
          widget: "markdown", 
          required: true,
          hint: "Der Hauptinhalt des Blog-Beitrags in Markdown-Format"
        }
  
  # Authors Collection
  - name: "authors"
    label: "Autoren"
    label_singular: "Autor"
    folder: "public/content/authors"
    create: true
    delete: false
    slug: "{{slug}}"
    identifier_field: "id"
    editor:
      preview: false
    fields:
      - { 
          label: "Autor-ID", 
          name: "id", 
          widget: "string", 
          required: true,
          pattern: ['^[a-z0-9_-]+$', "Nur Kleinbuchstaben, Zahlen, Unterstriche und Bindestriche"],
          hint: "Eindeutige Kennung für den Autor"
        }
      - { 
          label: "Name", 
          name: "name", 
          widget: "string", 
          required: true,
          hint: "Vollständiger Name des Autors"
        }
      - { 
          label: "E-Mail", 
          name: "email", 
          widget: "string", 
          required: true,
          pattern: ['^[^\s@]+@[^\s@]+\.[^\s@]+$', "Gültige E-Mail-Adresse erforderlich"],
          hint: "E-Mail-Adresse des Autors"
        }
      - { 
          label: "Biografie", 
          name: "bio", 
          widget: "text", 
          required: false,
          hint: "Kurze Beschreibung des Autors"
        }
      - { 
          label: "Profilbild", 
          name: "avatar", 
          widget: "image", 
          required: false,
          hint: "Profilbild des Autors"
        }
      - { 
          label: "Website", 
          name: "website", 
          widget: "string", 
          required: false,
          pattern: ['^https?://.*', "Vollständige URL mit http:// oder https://"],
          hint: "Website des Autors"
        }
      - label: "Social Media"
        name: "social"
        widget: "object"
        collapsed: true
        required: false
        fields:
          - { 
              label: "Instagram", 
              name: "instagram", 
              widget: "string", 
              required: false,
              hint: "Instagram Username (ohne @)"
            }
          - { 
              label: "LinkedIn", 
              name: "linkedin", 
              widget: "string", 
              required: false,
              hint: "LinkedIn Profil URL"
            }
          - { 
              label: "Twitter", 
              name: "twitter", 
              widget: "string", 
              required: false,
              hint: "Twitter Username (ohne @)"
            }

# Editor configuration
editor:
  preview: true

# Slug configuration
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

# Search configuration
search: true

# Show preview links
show_preview_links: true